### ISSUE TITLE
Migrating in-line TODOs into GitHub issues

### ISSUE THREAD

**Issue by wbnns** [nasa-jpl/react-stellar#23]
@AaronPlave 

Heya! Was looking through the code base and was curious if it would be a welcome change to migrate in-line TODOs into their own respective GitHub issues to make them easier for others to discover and potentially resolve?

**Comment by AaronPlave** [comment]
Hey @wbnns, go for it! Looks like we only have a few TODOs at the moment but probably worth surfacing them. Thanks for pitching in!
