### ISSUE TITLE
Tooltip text color is white

### ISSUE THREAD

**Issue by msolano00** [nasa-jpl/react-stellar#33]
### Issue description
Currently the tooltip text color is set to white, making the lecture of the tooltip content imposible.
<img width="196" alt="image" src="https://github.com/nasa-jpl/react-stellar/assets/2273023/890a77e6-2499-4aac-ba02-a30459a8d1da">

### Expected behavior
The tooltip text should be easy and clear to read
<img width="208" alt="image" src="https://github.com/nasa-jpl/react-stellar/assets/2273023/31f75004-20f4-4541-b8df-c0b1457fa9ea">

PS: I have a fix for this if the project is open for contribution

**Comment by AaronPlave** [comment]
Issue may be that you're looking at the story in dark mode which is not yet supported. Will be addressed by #36

**Comment by msolano00** [comment]
@AaronPlave that was it, thanks!
