### ISSUE TITLE
Date Picker

### ISSUE THREAD

**Issue by AaronPlave** [nasa-jpl/react-stellar#44]
Implement basic date time picker

**Comment by rtapella** [comment]
This is just a single date/time picker?

Time range?
Short time range vs. long time range? Type in & GUI support? etc.

**Comment by AaronPlave** [comment]
This is definitely a can of worms and could end up being quite complicated depending on use cases. I think the first pass of this would involve finding a good existing component to build off of that supports date range + time picker with typing + the popover selection. The project driving the use case is interested in this for Earth science applications so there wouldn't be a focus on alternative times though perhaps that could be supported in the future.

**Comment by duranb** [comment]
I've had some good success with [`react-day-picker`](https://react-day-picker.js.org/). My current [implementation](https://github.jpl.nasa.gov/397/eas-ui-utils/blob/develop/src/components/inputs/datePicker/datePicker.tsx) looks like [this](https://github.jpl.nasa.gov/pages/397/eas-ui-utils/?path=/story/atoms-inputs-datepicker--scet-date-picker). It is a little finicky to customize, but so far it's worked out for us.
