### ISSUE TITLE
Build Icons Error

### ISSUE THREAD

**Issue by eddiesarevalo** [nasa-jpl/react-stellar#46]
Hello! 

I am having a problem building icons, I am hoping you can help me.

I get this error when running `npm run build-icons`:
<img width="1494" alt="Screenshot 2024-03-25 at 1 42 44 PM" src="https://github.com/nasa-jpl/react-stellar/assets/5596893/f7c8eb78-6a73-4912-a999-c4a7576368e1">

What seems to be happening is that the SVGR package is expected to run in commonjs, aka require() syntax but because the package.json file is set to `"type":"module"` it errors out. Removing that line or setting it to `commonjs `allows it to run without errors but then the build-lib script no longer works as it expects module aka import() syntax.

Is there some extra script that needs to be run before building icons?

For now I was able to get around this by setting it to type”commonjs” then back to “module” when building icons.

`"build-icons": "npm pkg set 'type'='commonjs' && svgr -d ./src/components/Icons/ node_modules/@nasapds/wds/icons/ && npm pkg set 'type'='module'",`

I don't think this was the intention though. Are both build icons and build lib scripts meant to run on type module?

**To reproduce:** 

Follow the instructions in the readme https://github.com/nasa-jpl/react-stellar?tab=readme-ov-file#developing-components exactly the same and then run the build command `npm run build-icons`

Any help is appreciated. Thank you for your time!

**Comment by AaronPlave** [comment]
@eddiesarevalo fixed in v1.1.7
